name: Reusable Tag Release

on:
  workflow_call:
    inputs:
      tag:
        required: false
        type: string
        default: "v0.0.0"
      tag_message:
        required: false
        type: string
        default: "Releasing version"
      on_tag_exists:
        required: false
        type: string
        default: "skip"
    secrets:
      GIT_TOKEN:
        required: true

jobs:
  create_tag:
    runs-on: ubuntu-22.04
    name: Tag Release

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Create Tag
        uses: joutvhu/create-tag@v1.0.2
        with:
          tag_name: ${{ inputs.tag }}
          message: ${{ inputs.tag_message }}
          on_tag_exists: ${{ inputs.on_tag_exists }}
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
